import { afterEach, describe, expect, it, vi } from 'vitest';
import { EdgeBlockedError } from '@chrischall/mcp-utils';
import { createTestHarness, parseToolResult } from './helpers.js';
import { CrownTownClient } from '../src/client.js';
import { AuthManager, LoginRejectedError, PortalHttpError } from '../src/auth.js';
import type { PortalRequest, PortalResponse, PortalTransport } from '../src/transport.js';
import { registerHealthcheckTools } from '../src/tools/healthcheck.js';
import { DASHBOARD_HTML, LOGIN_PAGE_HTML } from './fixtures/pages.js';

/**
 * A real CloudFront refusal page, trimmed. The edge in front of the portal
 * answers with it BEFORE Django sees the request, so it must never read as a
 * bad password and never cost a login (chrischall/mcp-host#1015).
 */
const CLOUDFRONT_BLOCK = `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 3xAmPlE_rEqUeSt_iD==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>`;

function res(partial: Partial<PortalResponse> = {}): PortalResponse {
  return { status: 200, body: '', url: 'https://portal.crowntowncompost.com/accounts/', setCookie: [], contentType: 'text/html', ...partial };
}
const blocked = (status = 403) => res({ status, body: CLOUDFRONT_BLOCK });

const LOGIN_OK = res({ status: 302, location: '/accounts/', setCookie: ['sessionid=SESSION; Path=/; HttpOnly'] });
const LOGIN_REJECTED = res({ status: 200, body: LOGIN_PAGE_HTML, url: 'https://portal.crowntowncompost.com/accounts/login/' });

/** Route the login page GET, the login POST, and everything else; count logins. */
class Router implements PortalTransport {
  logins = 0;
  constructor(
    private readonly opts: {
      loginGet?: () => PortalResponse;
      loginPost?: () => PortalResponse;
      page: () => PortalResponse;
    },
  ) {}
  async request(req: PortalRequest): Promise<PortalResponse> {
    if (req.path.includes('/accounts/login/')) {
      if (req.method === 'GET') return (this.opts.loginGet ?? (() => res({ body: LOGIN_PAGE_HTML, setCookie: ['csrftoken=C; Path=/'] })))();
      this.logins++;
      return (this.opts.loginPost ?? (() => LOGIN_OK))();
    }
    return this.opts.page();
  }
}

function clientFor(t: Router, creds: { username?: string; password?: string; sessionCookie?: string } = { username: 'u', password: 'p' }) {
  return new CrownTownClient({ transport: t, auth: new AuthManager(t, creds) });
}

let h: Awaited<ReturnType<typeof createTestHarness>> | undefined;
afterEach(async () => {
  await h?.close();
  h = undefined;
  vi.unstubAllEnvs();
});

async function healthcheck(client: CrownTownClient) {
  h = await createTestHarness((s) => registerHealthcheckTools(s, client));
  return parseToolResult(await h.callTool('crowntown_healthcheck', {})) as Record<string, any>;
}

describe('edge blocks (CDN/WAF refusal pages)', () => {
  it('a blocked login is an EdgeBlockedError, not "check your CROWNTOWN_PASSWORD"', async () => {
    const t = new Router({ loginGet: () => blocked(), loginPost: () => blocked(), page: () => res({ body: DASHBOARD_HTML }) });
    const err = await clientFor(t).fetchHtml('/accounts/').catch((e: unknown) => e);
    expect(err).toBeInstanceOf(EdgeBlockedError);
    expect((err as EdgeBlockedError).vendor).toBe('CloudFront');
    expect(t.logins).toBe(0); // the credentials were never POSTed into a block
  });

  it('a block on the login POST is an EdgeBlockedError too', async () => {
    const t = new Router({ loginPost: () => blocked(), page: () => res({ body: DASHBOARD_HTML }) });
    await expect(clientFor(t).fetchHtml('/accounts/')).rejects.toBeInstanceOf(EdgeBlockedError);
  });

  it('a block on a page keeps the session — no re-login, no "page may have moved"', async () => {
    let block = true;
    const t = new Router({ page: () => (block ? blocked() : res({ body: DASHBOARD_HTML })) });
    const client = clientFor(t);
    const err = await client.fetchHtml('/accounts/').catch((e: unknown) => e);
    expect(err).toBeInstanceOf(EdgeBlockedError);
    expect((err as Error).message).not.toMatch(/may have moved/);
    block = false;
    await expect(client.fetchHtml('/accounts/')).resolves.toContain('Active');
    expect(t.logins).toBe(1);
  });

  it('control: a genuine non-block 404 still reads as a request failure', async () => {
    const t = new Router({ page: () => res({ status: 404, body: '<h1>Not Found</h1>' }) });
    const err = await clientFor(t).fetchHtml('/nope/').catch((e: unknown) => e);
    expect(err).not.toBeInstanceOf(EdgeBlockedError);
    expect((err as Error).message).toMatch(/HTTP 404/);
  });
});

describe('crowntown_healthcheck reports a kind', () => {
  it('ok: keeps authenticated / account_status / service_addresses beside the shared envelope', async () => {
    const out = await healthcheck(clientFor(new Router({ page: () => res({ body: DASHBOARD_HTML }) })));
    expect(out).toMatchObject({
      ok: true,
      authenticated: true,
      account_status: 'Active',
      service_addresses: 2,
      credential: { source: 'password', resolved: true },
    });
    expect(out.error).toBeUndefined();
  });

  it('ok but unparsed: says the markup may have changed', async () => {
    const out = await healthcheck(clientFor(new Router({ page: () => res({ body: '<html><body>hi</body></html>' }) })));
    expect(out).toMatchObject({ ok: true, authenticated: true });
    expect(out.hint).toMatch(/did not parse/);
  });

  it('edge_blocked: a block page is not reported as bad credentials', async () => {
    const out = await healthcheck(clientFor(new Router({ loginGet: () => blocked(), page: () => res({ body: DASHBOARD_HTML }) })));
    expect(out).toMatchObject({ ok: false, authenticated: false });
    expect(out.error).toMatchObject({ kind: 'edge_blocked', detail: { vendor: 'CloudFront' } });
    expect(out.hint).toMatch(/CDN\/WAF/);
    expect(out.hint).not.toMatch(/CROWNTOWN_PASSWORD/);
  });

  it('edge_blocked: a block on the dashboard probe', async () => {
    const out = await healthcheck(clientFor(new Router({ page: () => blocked(403) })));
    expect(out.error).toMatchObject({ kind: 'edge_blocked' });
  });

  it('control — credential_rejected: Django re-rendered the login form', async () => {
    const out = await healthcheck(clientFor(new Router({ loginPost: () => LOGIN_REJECTED, page: () => res({ body: DASHBOARD_HTML }) })));
    expect(out.error).toMatchObject({ kind: 'credential_rejected' });
    expect(out.hint).toMatch(/CROWNTOWN_USERNAME/);
  });

  it('session_expired: a supplied session cookie the portal no longer honours', async () => {
    const t = new Router({ page: () => res({ body: LOGIN_PAGE_HTML, url: 'https://portal.crowntowncompost.com/accounts/login/?next=/accounts/' }) });
    const out = await healthcheck(clientFor(t, { sessionCookie: 'sessionid=dead' }));
    expect(out.credential).toMatchObject({ source: 'session_cookie', resolved: true });
    expect(out.error).toMatchObject({ kind: 'session_expired' });
    expect(out.hint).toMatch(/CROWNTOWN_SESSION_COOKIE/);
  });

  it('no_credential: nothing configured, nothing probed', async () => {
    vi.stubEnv('CROWNTOWN_USERNAME', '');
    vi.stubEnv('CROWNTOWN_PASSWORD', '');
    vi.stubEnv('CROWNTOWN_SESSION_COOKIE', '');
    const t = new Router({ page: () => res({ body: DASHBOARD_HTML }) });
    const spy = vi.spyOn(t, 'request');
    const out = await healthcheck(clientFor(t, {}));
    expect(out.error).toMatchObject({ kind: 'no_credential' });
    expect(out).toMatchObject({ ok: false, authenticated: false, credential: { source: null } });
    expect(out.hint).toMatch(/CROWNTOWN_SESSION_COOKIE/);
    expect(spy).not.toHaveBeenCalled();
  });
});

describe('re-login after an expired session surfaces the actionable failure', () => {
  const EXPIRED = () => res({ body: LOGIN_PAGE_HTML, url: 'https://portal.crowntowncompost.com/accounts/login/?next=/accounts/' });

  it('session_expired: a fresh login that still lands on the login page', async () => {
    const out = await healthcheck(clientFor(new Router({ page: EXPIRED })));
    expect(out.error).toMatchObject({ kind: 'session_expired' });
  });

  it('credential_rejected: the cookie died and the password is refused on re-login', async () => {
    const t = new Router({ loginPost: () => LOGIN_REJECTED, page: EXPIRED });
    const out = await healthcheck(clientFor(t, { sessionCookie: 'sessionid=dead', username: 'u', password: 'bad' }));
    expect(out.error).toMatchObject({ kind: 'credential_rejected' });
  });

  it('edge_blocked: the cookie died and the re-login meets a block page', async () => {
    const t = new Router({ loginGet: () => blocked(), page: EXPIRED });
    const err = await clientFor(t, { sessionCookie: 'sessionid=dead', username: 'u', password: 'p' })
      .fetchHtml('/accounts/')
      .catch((e: unknown) => e);
    expect(err).toBeInstanceOf(EdgeBlockedError);
    expect(t.logins).toBe(0);
  });

  it('control: any other re-login failure keeps the manager default (the expired page → session error)', async () => {
    const t = new Router({ loginPost: () => res({ status: 403, body: 'CSRF verification failed' }), page: EXPIRED });
    const out = await healthcheck(clientFor(t, { sessionCookie: 'sessionid=dead', username: 'u', password: 'p' }));
    expect(out.error).toMatchObject({ kind: 'session_expired' });
  });
});

describe('login POST failures are classified by what the portal actually said', () => {
  const SITE_ERROR = (status: number) => () => res({ status, body: '<h1>Server Error (' + status + ')</h1>' });

  it.each([500, 502, 503])('a genuine %i on the login POST is http, never credential_rejected', async (status) => {
    const t = new Router({ loginPost: SITE_ERROR(status), page: () => res({ body: DASHBOARD_HTML }) });
    const err = await clientFor(t).fetchHtml('/accounts/').catch((e: unknown) => e);
    expect(err).toBeInstanceOf(PortalHttpError);
    expect(err).not.toBeInstanceOf(LoginRejectedError);
    expect((err as PortalHttpError).status).toBe(status);
    expect((err as Error).message).not.toMatch(/CROWNTOWN_PASSWORD/);

    const out = await healthcheck(clientFor(new Router({ loginPost: SITE_ERROR(status), page: () => res({ body: DASHBOARD_HTML }) })));
    expect(out.error).toMatchObject({ kind: 'http' });
    expect(out.hint).not.toMatch(/CROWNTOWN_PASSWORD/);
  });

  it('a non-block 403 on the login POST (Django CSRF/Referer) is http, not credential_rejected', async () => {
    const t = new Router({ loginPost: () => res({ status: 403, body: 'CSRF verification failed' }), page: () => res({ body: DASHBOARD_HTML }) });
    const err = await clientFor(t).fetchHtml('/accounts/').catch((e: unknown) => e);
    expect(err).toBeInstanceOf(PortalHttpError);
    expect((err as PortalHttpError).status).toBe(403);
    const out = await healthcheck(clientFor(new Router({ loginPost: () => res({ status: 403, body: 'CSRF verification failed' }), page: () => res({ body: DASHBOARD_HTML }) })));
    expect(out.error).toMatchObject({ kind: 'http' });
    expect(out.hint).toMatch(/CSRF/);
  });

  it('a block page on the login POST is edge_blocked', async () => {
    const out = await healthcheck(clientFor(new Router({ loginPost: () => blocked(), page: () => res({ body: DASHBOARD_HTML }) })));
    expect(out.error).toMatchObject({ kind: 'edge_blocked', detail: { vendor: 'CloudFront' } });
  });

  it('a 200 that is not the login form and set no session is not blamed on the password', async () => {
    const t = new Router({ loginPost: () => res({ status: 200, body: '<p>Maintenance</p>' }), page: () => res({ body: DASHBOARD_HTML }) });
    const err = await clientFor(t).fetchHtml('/accounts/').catch((e: unknown) => e);
    expect(err).toBeInstanceOf(Error);
    expect(err).not.toBeInstanceOf(LoginRejectedError);
  });

  it('control — the re-rendered login form is still LoginRejectedError / credential_rejected', async () => {
    const t = new Router({ loginPost: () => LOGIN_REJECTED, page: () => res({ body: DASHBOARD_HTML }) });
    const err = await clientFor(t).fetchHtml('/accounts/').catch((e: unknown) => e);
    expect(err).toBeInstanceOf(LoginRejectedError);
    const out = await healthcheck(clientFor(new Router({ loginPost: () => LOGIN_REJECTED, page: () => res({ body: DASHBOARD_HTML }) })));
    expect(out.error).toMatchObject({ kind: 'credential_rejected' });
  });

  it('a 5xx on a portal page carries its status and reads http', async () => {
    const out = await healthcheck(clientFor(new Router({ page: () => res({ status: 502, body: 'Bad Gateway' }) })));
    expect(out.error).toMatchObject({ kind: 'http' });
    expect(out.probe).toMatchObject({ status: 502 });
  });
});
